### ISSUE TITLE
Archivos de parcial vacios

### ISSUE THREAD

**Issue by Lautron** [ExamenesViejos-FaMAF-Computacion/ExamenesViejos_AlgoritmosYEstructurasDeDatos2_FaMAF#3]
## Problema
Los archivos del **ej1** del **Parcial 2 2021-06-03** del laboratorio estan vacios.
## Ubicacion
[ExamenesViejos_AlgoritmosYEstructurasDeDatos2_FaMAF/Laboratorio/Parcial 2 2021-06-03/parcial2-ej1/
](https://github.com/ExamenesViejos-FaMAF-Computacion/ExamenesViejos_AlgoritmosYEstructurasDeDatos2_FaMAF/tree/e05a1384bfa5bd76e8590323aa538eeda6c2309b/Laboratorio/Parcial%202%202021-06-03/parcial2-ej1)

**Comment by IvanRenison** [comment]
Es cierto, gracias, voy a ver si encuentro los originales

**Comment by IvanRenison** [comment]
Listo, ahí los encontré y los agregué. Muchas gracias
